name: CI/CD Pipeline
run-name: ${{ github.actor }} is running the CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo - Workflow trigger info
      run: |
        echo "Job triggered by event: ${{ github.event_name }}"
        echo "Running on OS: ${{ runner.os }}"
        echo "Branch: ${{ github.ref }}"
        echo "Repository: ${{ github.repository }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Successful clone
      run: echo "Repository has been cloned successfully"

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Dependencies installed"

    - name: Check and free port 8000
      run: |
        echo "Checking if port 8000 is in use..."
        if sudo lsof -i :8000; then
          echo "Port 8000 is busy, killing the process using it..."
          sudo fuser -k 8000/tcp
        else
          echo "Port 8000 is free"
        fi


    - name: Uvicorn smoke test
      run: |
        echo "Launching uvicorn as a smoke test"
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
        sleep 10

    - name: Testing endpoint
      run: |
        curl -f http://localhost:8000/

    - name: Test predict
      run: |
        curl -f -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -f '{"model_choice": "xgb", "features": [2026, 5, 26, 12983, "Saturday", "Yes", 1, 0, 121, 9841, 0.98372, 0.103827]}'
          
    - name: Echo - CI done
      run: echo "CI pipeline completed successfully"

    - name: Render Deployment
      env: 
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -f -X POST https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \
        -H "Authorization: Bearer ${RENDER_API_KEY}" \
        -H "Accept: application/json"


    - name: CI/CD Pipleline complete
      run: echo "CI/CD Pipeline successfully fulfilled"